% Author: Eilam Morag
% July 28, 2016
% Purpose: Generates the homepage website for the program. This will list
% links to all channels that have been investigated. Generates
% channelNav.php

function genChanNavHTML(path)
       text = [ '<!DOCTYPE html>\n', ...
                '<html>\n', ...
                '<head>\n', ...
                    '<title>Channel Navigation</title>\n', ...
                    '<link rel="stylesheet" type="text/css" href="', path, 'channelNav.css"/>\n', ...
                '</head>\n', ...
                '<body>\n', ...
                    '<div class = "header">\n', ...
                        '<h1>\n', ...
                            'LIGO Spectral Line Artifact Investigation\n', ...
                        '</h1>\n', ...
                    '</div>\n', ...
                    '<h2>\n', ...
                        'Channel Navigation\n', ...
                    '</h2>\n', ...
                    '<div class = "navBlock">\n', ...
                        '<table style="width:50%">\n', ...
                            '<tr>\n', ...
                                '<th>Channels</th>\n', ...
                            '</tr>\n', ...
                            '<?php\n', ...
                                '$directories = scandir("', path, '");\n', ...
                                'foreach ($directories as $key => $folder) {\n', ...
                                    'if ($key > 1 && fnmatch("*.css", $folder) == FALSE && fnmatch("*.php", $folder) == FALSE) {\n', ...
                                        '$link = $folder;\n', ...
                                        '$path = $folder;\n', ...
                                        'echo "<tr><a href=$path>\n', ...
                                                    '<td><a href=$path>$link</a></td>\n', ...
                                                '</tr>";\n', ...
                                    '}\n', ...
                                '}\n', ...
                            '?>\n', ...
                        '</table>\n', ...
                    '</div>\n', ...
            '</body>\n', ...
            '</html>\n'];

        
    filename = [path, 'channelNav.php'];
    disp(['Creating file ', filename]);
    fileID = fopen(filename, 'w');
    fprintf(fileID, text);
    fclose(fileID);
end